# Simple ZIP Report Creator
# Creates a downloadable ZIP file containing test reports

param(
    [string]$OutputPath = ".",
    [switch]$OpenFolder = $false
)

Write-Host "Creating downloadable report ZIP..." -ForegroundColor Green

# Check if reports exist
$hasInteractive = Test-Path "allure-report"
$hasSingle = Test-Path "allure-report-single"

if (-not $hasInteractive -and -not $hasSingle) {
    Write-Host "ERROR: No reports found. Please run: npm run allure:generate" -ForegroundColor Red
    exit 1
}

# Create timestamp for unique filename
$timestamp = Get-Date -Format "yyyy-MM-dd_HH-mm-ss"
$zipName = "allure-report-$timestamp.zip"
$zipPath = Join-Path $OutputPath $zipName

# Create temporary directory for packaging
$tempDir = Join-Path $env:TEMP "allure-package-$timestamp"
New-Item -ItemType Directory -Path $tempDir -Force | Out-Null

try {
    Write-Host "Preparing package contents..." -ForegroundColor Cyan
    
    # Copy interactive report if exists
    if ($hasInteractive) {
        Write-Host "   Adding interactive report..." -ForegroundColor Yellow
        $interactiveDestination = Join-Path $tempDir "interactive-report"
        Copy-Item -Path "allure-report" -Destination $interactiveDestination -Recurse
    }
    
    # Copy single file report if exists
    if ($hasSingle) {
        Write-Host "   Adding single page report..." -ForegroundColor Yellow
        Copy-Item -Path "allure-report-single\index.html" -Destination "$tempDir\single-page-report.html"
    }
    
    # Create simple README file
    $readmeLines = @(
        "# Test Report Package",
        "",
        "Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')",
        "Package: allure-report-$timestamp",
        "",
        "## Contents:",
        ""
    )
    
    if ($hasInteractive) {
        $readmeLines += @(
            "- interactive-report/ - Full featured Allure report",
            "  Open index.html in browser for complete experience",
            "  Best viewed via HTTP server",
            ""
        )
    }
    
    if ($hasSingle) {
        $readmeLines += @(
            "- single-page-report.html - Self-contained single file",
            "  Opens directly in any browser",
            "  Easy to share via email or cloud storage",
            ""
        )
    }
    
    $readmeLines += @(
        "## How to View:",
        "",
        "### Quick Start:",
        "1. Double-click single-page-report.html",
        "2. Opens immediately in your default browser",
        "",
        "### Interactive Report:",
        "1. For best experience, use an HTTP server",
        "2. Install VS Code + Live Server extension (recommended)",
        "3. Or run: npx serve . (in this folder)",
        "",
        "## Sharing Options:",
        "",
        "- Email: Attach single-page-report.html",
        "- Cloud: Upload entire ZIP to Google Drive, OneDrive, etc.",
        "- USB: Copy to USB drive for offline sharing",
        "- Web: Upload to any web hosting service",
        "",
        "---",
        "Generated by Playwright + Allure Test Framework"
    )
    
    $readmeContent = $readmeLines -join "`n"
    Set-Content -Path "$tempDir\README.txt" -Value $readmeContent
    
    # Create simple launcher HTML
    if ($hasInteractive) {
        $htmlContent = @"
<!DOCTYPE html>
<html>
<head>
    <title>Test Report Launcher</title>
    <style>
        body { font-family: Arial, sans-serif; max-width: 600px; margin: 50px auto; padding: 20px; }
        .btn { display: inline-block; padding: 15px 30px; margin: 10px; background: #0052cc; 
               color: white; text-decoration: none; border-radius: 5px; }
        .btn:hover { background: #0065ff; }
        .btn.green { background: #36b37e; }
        .info { background: #f0f0f0; padding: 20px; border-radius: 5px; margin: 20px 0; }
    </style>
</head>
<body>
    <h1>Test Report Launcher</h1>
    
    <div class="info">
        <p><strong>Quick Access:</strong></p>
        <a href="./single-page-report.html" class="btn green">Single Page Report</a>
        <a href="./interactive-report/index.html" class="btn">Interactive Report</a>
    </div>
    
    <div class="info">
        <p><strong>For best experience with interactive report:</strong></p>
        <ol>
            <li>Install VS Code + Live Server extension</li>
            <li>Right-click this folder, select "Open with Code"</li>
            <li>Right-click any HTML file, select "Open with Live Server"</li>
        </ol>
    </div>
    
    <p>Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')</p>
</body>
</html>
"@
        
        Set-Content -Path "$tempDir\index.html" -Value $htmlContent
    }
    
    Write-Host "Creating ZIP file..." -ForegroundColor Cyan
    
    # Create ZIP file
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    [System.IO.Compression.ZipFile]::CreateFromDirectory($tempDir, $zipPath)
    
    # Clean up temp directory
    Remove-Item -Path $tempDir -Recurse -Force
    
    Write-Host ""
    Write-Host "SUCCESS: ZIP file created!" -ForegroundColor Green
    Write-Host "File: $zipPath" -ForegroundColor Yellow
    Write-Host "Size: $([math]::Round((Get-Item $zipPath).Length / 1MB, 2)) MB" -ForegroundColor Yellow
    
    Write-Host ""
    Write-Host "Ready to share via:" -ForegroundColor Cyan
    Write-Host "   Email (if under size limit)" -ForegroundColor White
    Write-Host "   Google Drive, OneDrive, Dropbox" -ForegroundColor White
    Write-Host "   USB drive or network share" -ForegroundColor White
    Write-Host "   File hosting service" -ForegroundColor White
    
    if ($OpenFolder) {
        Write-Host ""
        Write-Host "Opening folder..." -ForegroundColor Cyan
        Start-Process "explorer.exe" -ArgumentList "/select,`"$zipPath`""
    }
    
    return $zipPath

} catch {
    Write-Host "ERROR: Failed to create ZIP file: $_" -ForegroundColor Red
    if (Test-Path $tempDir) {
        Remove-Item -Path $tempDir -Recurse -Force
    }
    exit 1
}